### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by adborden**
Fix the tests and setup travis. You can run them with:

    $ npm test

This does change the default way tests are run. Karma now runs once and exists. If you want the old behavior of continuous integration-style auto watch tests:

    $ gulp test --watch

### CODE REVIEW

**Comment by jnmarcus** [comment]
yay yay yay we have a travis badge (and travis)! :tada: 

This lgtm.  I'd be interested to hear your thoughts (and anyone else's) on removing bower from the workflow entirely, and relying solely on npm.  I think it would help reduce version conflicts of packages, and may help people new to the project get up and running faster, and without issues.  It may also help us test stable vs unstable releases, as we (and external packages) continue to update.

**Comment by jnmarcus** [comment]
before we merge this @adborden can you add the mainController files back in? I'm planning on using them, that's why they were just commented out, and not removed.

**Comment by adborden** [comment]
Files restored.

**Comment by adborden** [comment]
@tdooner is working on getting rid of bower.

**Pull request merged**
